version: "3.7"

services:
  # Backend API
  clustite-backend-api:
    build: ./
    command: npm start
    container_name: backend
    environment:
      POSTGRES_URI: postgres://emmanuelakhigbe:secret@postgres:5432/clustite-pg-database
      REDIS_URI: redis://redis:6379
      JWT_SECRET: "theMostSecureJWTSecret"
    links:
      - postgres
      - redis
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/clustite-backend
    working_dir: /usr/src/clustite-backend
  # PostgreSQL service
  postgres:
    environment:
      POSTGRES_USER: emmanuelakhigbe
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: clustite-pg-database
      POSTGRES_HOST: postgres
    build: ./src/datasources/postgres
    ports:
      - "5432:5432"
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
